# Generated by Django 5.1.4 on 2025-07-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('history', models.TextField()),
                ('established_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bowl_logos/')),
                ('stadium', models.CharField(max_length=100)),
                ('stadium_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('stadium_location', models.CharField(blank=True, max_length=100, null=True)),
                ('stadium_image', models.ImageField(blank=True, null=True, upload_to='stadium_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('established_date', models.DateField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='division_logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('history', models.TextField()),
                ('home_page', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('established_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('established_date', models.DateField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conference_logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('history', models.TextField()),
                ('home_page', models.URLField()),
                ('teams_count', models.PositiveIntegerField(default=0)),
                ('championships_count', models.PositiveIntegerField(default=0)),
                ('rivalries_count', models.PositiveIntegerField(default=0)),
                ('championships', models.TextField(blank=True, null=True)),
                ('rivalries', models.TextField(blank=True, null=True)),
                ('home_stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFB.division')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFB.organization'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_stadium', models.CharField(max_length=100)),
                ('home_city', models.CharField(max_length=100)),
                ('home_state', models.CharField(max_length=50)),
                ('home_country', models.CharField(default='USA', max_length=50)),
                ('team_color', models.CharField(blank=True, max_length=50, null=True)),
                ('mascot', models.CharField(blank=True, max_length=100, null=True)),
                ('team_website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('home_stadium_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('home_stadium_location', models.CharField(blank=True, max_length=100, null=True)),
                ('home_stadium_image', models.ImageField(null=True, upload_to='stadium_images/')),
                ('established_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('history', models.TextField()),
                ('championships', models.TextField(blank=True, null=True)),
                ('rivalries', models.TextField(blank=True, null=True)),
                ('home_page', models.URLField()),
                ('championships_count', models.PositiveIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFB.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Rilvalry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rivalry_name', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='CFB.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='CFB.team')),
            ],
        ),
    ]
