# Generated by Django 5.1.4 on 2025-07-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rilvalry',
            new_name='Rivalry',
        ),
    ]
